server:
  port: 8094
spring:
  application:
    name: order
  cloud:
    nacos:
      config:
        group: zpain
        namespace: ${spring.cloud.nacos.discovery.namespace}
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
      discovery:
        namespace: 164265e8-9bd8-424d-a687-94cca4083a21
        server-addr: localhost:8848
        group: zpain